mod common;
use common::{MakeCirclesBuilder, make_circles};
use locus::prelude::*;
use raylib::prelude::*;

const IMAGE_SIZE: i32 = 90;
const WIDTH: i32 = 16 * IMAGE_SIZE;
const HEIGHT: i32 = 9 * IMAGE_SIZE;
/// Demonstrates all the new text features:
/// - Chart title, x-axis label, y-axis label
/// - Tick labels on both axes (auto-generated by `TickLabels`)
/// - Legend with colour swatches
/// - Data-space annotation with leader arrow
#[allow(clippy::cast_precision_loss)]
fn main() {
    let (mut rl, rl_thread) = raylib::init()
        .width(WIDTH)
        .height(HEIGHT)
        .title("Locus — Text Showcase")
        .build();
    let dataset = make_circles(
        &MakeCirclesBuilder::default()
            .n_circles(5)
            .radius(2.0..8.0)
            .with_equal_ranges(-10.0..10.0)
            .n_samples(2000)
            .build()
            .unwrap(),
    );

    let scatter = ScatterPlot::new(&dataset);
    let graph = Graph::new(scatter);
    let colorscheme = GITHUB_DARK.clone();

    let axis = Axis::fitting(
        dataset.range_min.x..dataset.range_max.x,
        dataset.range_min.y..dataset.range_max.y,
    );

    let ticks = TickLabels::new(axis);

    while !rl.window_should_close() {
        let mut d = rl.begin_drawing(&rl_thread);
        d.clear_background(colorscheme.background);

        graph.plot(
            &mut d,
            &GraphBuilder::default()
                .viewport(
                    Viewport::new(10.0, 10.0, (WIDTH - 20) as f32, (HEIGHT - 20) as f32)
                        .with_margins(Margins {
                            left: 60.0,
                            right: 20.0,
                            top: 50.0,
                            bottom: 55.0,
                        }),
                )
                .colorscheme(colorscheme.clone())
                // Axis + grid + ticks
                .axis(ConfiguredElement::with_defaults(axis))
                .grid(ConfiguredElement::with_defaults(GridLines::new(
                    axis,
                    Orientation::default(),
                )))
                .ticks(ConfiguredElement::with_defaults(ticks).configure(
                    |t: &mut locus::plottable::line::TickLabelsConfig| {
                        t.x_axis_scale = Scale::Linear;
                    },
                ))
                // Chart title
                .title("Circle Dispersion")
                // Axis labels
                .xlabel("X Coordinate")
                .ylabel("Y Coordinate")
                // Legend
                .legend(vec![
                    LegendEntry::new("Sample points", Color::RED),
                    LegendEntry::new("Cluster A", Color::SKYBLUE).with_shape(Shape::Rectangle),
                    LegendEntry::new("Cluster B", Color::GREEN).with_shape(Shape::Triangle),
                ])
                // Annotation with an arrow pointing to the origin
                .annotate_styled(
                    Annotation::at_data("Origin (0,0)", (1.0_f32, 1.0_f32)),
                    |c: &mut AnnotationConfig| {
                        c.line = Some(
                            AnnotLineConfigBuilder::default()
                                .target((0.0, 0.0).into())
                                .arrow(locus::plottable::line::Visibility::Visible)
                                .build()
                                .unwrap(),
                        )
                    },
                )
                // Subject rendering config
                .subject_configs(
                    ScatterPlotBuilder::default()
                        .fixed_color(Color::RED)
                        .fixed_size(3.0)
                        .build()
                        .unwrap(),
                )
                .build()
                .unwrap(),
        );
    }
}
